package org.fbi.aicqde.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fbi.aicqde.repository.model.AicQdeEnt;
import org.fbi.aicqde.repository.model.AicQdeEntExample;

public interface AicQdeEntMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.AIC_QDE_ENT
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    int countByExample(AicQdeEntExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.AIC_QDE_ENT
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    int deleteByExample(AicQdeEntExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.AIC_QDE_ENT
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    int deleteByPrimaryKey(String pregNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.AIC_QDE_ENT
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    int insert(AicQdeEnt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.AIC_QDE_ENT
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    int insertSelective(AicQdeEnt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.AIC_QDE_ENT
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    List<AicQdeEnt> selectByExample(AicQdeEntExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.AIC_QDE_ENT
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    AicQdeEnt selectByPrimaryKey(String pregNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.AIC_QDE_ENT
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    int updateByExampleSelective(@Param("record") AicQdeEnt record, @Param("example") AicQdeEntExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.AIC_QDE_ENT
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    int updateByExample(@Param("record") AicQdeEnt record, @Param("example") AicQdeEntExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.AIC_QDE_ENT
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    int updateByPrimaryKeySelective(AicQdeEnt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.AIC_QDE_ENT
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    int updateByPrimaryKey(AicQdeEnt record);
}