package org.fbi.aicqde.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fbi.aicqde.repository.model.AicQdeInvester;
import org.fbi.aicqde.repository.model.AicQdeInvesterExample;

public interface AicQdeInvesterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.AIC_QDE_INVESTER
     *
     * @mbggenerated Mon Dec 09 09:10:11 CST 2013
     */
    int countByExample(AicQdeInvesterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.AIC_QDE_INVESTER
     *
     * @mbggenerated Mon Dec 09 09:10:11 CST 2013
     */
    int deleteByExample(AicQdeInvesterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.AIC_QDE_INVESTER
     *
     * @mbggenerated Mon Dec 09 09:10:11 CST 2013
     */
    int insert(AicQdeInvester record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.AIC_QDE_INVESTER
     *
     * @mbggenerated Mon Dec 09 09:10:11 CST 2013
     */
    int insertSelective(AicQdeInvester record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.AIC_QDE_INVESTER
     *
     * @mbggenerated Mon Dec 09 09:10:11 CST 2013
     */
    List<AicQdeInvester> selectByExample(AicQdeInvesterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.AIC_QDE_INVESTER
     *
     * @mbggenerated Mon Dec 09 09:10:11 CST 2013
     */
    int updateByExampleSelective(@Param("record") AicQdeInvester record, @Param("example") AicQdeInvesterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.AIC_QDE_INVESTER
     *
     * @mbggenerated Mon Dec 09 09:10:11 CST 2013
     */
    int updateByExample(@Param("record") AicQdeInvester record, @Param("example") AicQdeInvesterExample example);
}