package org.fbi.aicqde.repository.model;

import java.math.BigDecimal;

public class AicQdeEnt {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.AIC_QDE_ENT.PREG_NO
     *
     * @mbggenerated Mon Dec 09 09:10:11 CST 2013
     */
    private String pregNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.AIC_QDE_ENT.AREA_CODE
     *
     * @mbggenerated Mon Dec 09 09:10:11 CST 2013
     */
    private String areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.AIC_QDE_ENT.AIC_CODE
     *
     * @mbggenerated Mon Dec 09 09:10:11 CST 2013
     */
    private String aicCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.AIC_QDE_ENT.AIC_NAME
     *
     * @mbggenerated Mon Dec 09 09:10:11 CST 2013
     */
    private String aicName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.AIC_QDE_ENT.REG_NO
     *
     * @mbggenerated Mon Dec 09 09:10:11 CST 2013
     */
    private String regNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.AIC_QDE_ENT.ACT_NO
     *
     * @mbggenerated Mon Dec 09 09:10:11 CST 2013
     */
    private String actNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.AIC_QDE_ENT.ACT_BAL
     *
     * @mbggenerated Mon Dec 09 09:10:11 CST 2013
     */
    private BigDecimal actBal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.AIC_QDE_ENT.BANK_HOST_SN
     *
     * @mbggenerated Mon Dec 09 09:10:11 CST 2013
     */
    private String bankHostSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.AIC_QDE_ENT.BANK_NAME
     *
     * @mbggenerated Mon Dec 09 09:10:11 CST 2013
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.AIC_QDE_ENT.ENT_NAME
     *
     * @mbggenerated Mon Dec 09 09:10:11 CST 2013
     */
    private String entName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.AIC_QDE_ENT.TELLER_ID
     *
     * @mbggenerated Mon Dec 09 09:10:11 CST 2013
     */
    private String tellerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.AIC_QDE_ENT.BRANCH_ID
     *
     * @mbggenerated Mon Dec 09 09:10:11 CST 2013
     */
    private String branchId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.AIC_QDE_ENT.PREG_NO
     *
     * @return the value of FIS.AIC_QDE_ENT.PREG_NO
     *
     * @mbggenerated Mon Dec 09 09:10:11 CST 2013
     */
    public String getPregNo() {
        return pregNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.AIC_QDE_ENT.PREG_NO
     *
     * @param pregNo the value for FIS.AIC_QDE_ENT.PREG_NO
     *
     * @mbggenerated Mon Dec 09 09:10:11 CST 2013
     */
    public void setPregNo(String pregNo) {
        this.pregNo = pregNo == null ? null : pregNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.AIC_QDE_ENT.AREA_CODE
     *
     * @return the value of FIS.AIC_QDE_ENT.AREA_CODE
     *
     * @mbggenerated Mon Dec 09 09:10:11 CST 2013
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.AIC_QDE_ENT.AREA_CODE
     *
     * @param areaCode the value for FIS.AIC_QDE_ENT.AREA_CODE
     *
     * @mbggenerated Mon Dec 09 09:10:11 CST 2013
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.AIC_QDE_ENT.AIC_CODE
     *
     * @return the value of FIS.AIC_QDE_ENT.AIC_CODE
     *
     * @mbggenerated Mon Dec 09 09:10:11 CST 2013
     */
    public String getAicCode() {
        return aicCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.AIC_QDE_ENT.AIC_CODE
     *
     * @param aicCode the value for FIS.AIC_QDE_ENT.AIC_CODE
     *
     * @mbggenerated Mon Dec 09 09:10:11 CST 2013
     */
    public void setAicCode(String aicCode) {
        this.aicCode = aicCode == null ? null : aicCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.AIC_QDE_ENT.AIC_NAME
     *
     * @return the value of FIS.AIC_QDE_ENT.AIC_NAME
     *
     * @mbggenerated Mon Dec 09 09:10:11 CST 2013
     */
    public String getAicName() {
        return aicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.AIC_QDE_ENT.AIC_NAME
     *
     * @param aicName the value for FIS.AIC_QDE_ENT.AIC_NAME
     *
     * @mbggenerated Mon Dec 09 09:10:11 CST 2013
     */
    public void setAicName(String aicName) {
        this.aicName = aicName == null ? null : aicName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.AIC_QDE_ENT.REG_NO
     *
     * @return the value of FIS.AIC_QDE_ENT.REG_NO
     *
     * @mbggenerated Mon Dec 09 09:10:11 CST 2013
     */
    public String getRegNo() {
        return regNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.AIC_QDE_ENT.REG_NO
     *
     * @param regNo the value for FIS.AIC_QDE_ENT.REG_NO
     *
     * @mbggenerated Mon Dec 09 09:10:11 CST 2013
     */
    public void setRegNo(String regNo) {
        this.regNo = regNo == null ? null : regNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.AIC_QDE_ENT.ACT_NO
     *
     * @return the value of FIS.AIC_QDE_ENT.ACT_NO
     *
     * @mbggenerated Mon Dec 09 09:10:11 CST 2013
     */
    public String getActNo() {
        return actNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.AIC_QDE_ENT.ACT_NO
     *
     * @param actNo the value for FIS.AIC_QDE_ENT.ACT_NO
     *
     * @mbggenerated Mon Dec 09 09:10:11 CST 2013
     */
    public void setActNo(String actNo) {
        this.actNo = actNo == null ? null : actNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.AIC_QDE_ENT.ACT_BAL
     *
     * @return the value of FIS.AIC_QDE_ENT.ACT_BAL
     *
     * @mbggenerated Mon Dec 09 09:10:11 CST 2013
     */
    public BigDecimal getActBal() {
        return actBal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.AIC_QDE_ENT.ACT_BAL
     *
     * @param actBal the value for FIS.AIC_QDE_ENT.ACT_BAL
     *
     * @mbggenerated Mon Dec 09 09:10:11 CST 2013
     */
    public void setActBal(BigDecimal actBal) {
        this.actBal = actBal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.AIC_QDE_ENT.BANK_HOST_SN
     *
     * @return the value of FIS.AIC_QDE_ENT.BANK_HOST_SN
     *
     * @mbggenerated Mon Dec 09 09:10:11 CST 2013
     */
    public String getBankHostSn() {
        return bankHostSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.AIC_QDE_ENT.BANK_HOST_SN
     *
     * @param bankHostSn the value for FIS.AIC_QDE_ENT.BANK_HOST_SN
     *
     * @mbggenerated Mon Dec 09 09:10:11 CST 2013
     */
    public void setBankHostSn(String bankHostSn) {
        this.bankHostSn = bankHostSn == null ? null : bankHostSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.AIC_QDE_ENT.BANK_NAME
     *
     * @return the value of FIS.AIC_QDE_ENT.BANK_NAME
     *
     * @mbggenerated Mon Dec 09 09:10:11 CST 2013
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.AIC_QDE_ENT.BANK_NAME
     *
     * @param bankName the value for FIS.AIC_QDE_ENT.BANK_NAME
     *
     * @mbggenerated Mon Dec 09 09:10:11 CST 2013
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.AIC_QDE_ENT.ENT_NAME
     *
     * @return the value of FIS.AIC_QDE_ENT.ENT_NAME
     *
     * @mbggenerated Mon Dec 09 09:10:11 CST 2013
     */
    public String getEntName() {
        return entName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.AIC_QDE_ENT.ENT_NAME
     *
     * @param entName the value for FIS.AIC_QDE_ENT.ENT_NAME
     *
     * @mbggenerated Mon Dec 09 09:10:11 CST 2013
     */
    public void setEntName(String entName) {
        this.entName = entName == null ? null : entName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.AIC_QDE_ENT.TELLER_ID
     *
     * @return the value of FIS.AIC_QDE_ENT.TELLER_ID
     *
     * @mbggenerated Mon Dec 09 09:10:11 CST 2013
     */
    public String getTellerId() {
        return tellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.AIC_QDE_ENT.TELLER_ID
     *
     * @param tellerId the value for FIS.AIC_QDE_ENT.TELLER_ID
     *
     * @mbggenerated Mon Dec 09 09:10:11 CST 2013
     */
    public void setTellerId(String tellerId) {
        this.tellerId = tellerId == null ? null : tellerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.AIC_QDE_ENT.BRANCH_ID
     *
     * @return the value of FIS.AIC_QDE_ENT.BRANCH_ID
     *
     * @mbggenerated Mon Dec 09 09:10:11 CST 2013
     */
    public String getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.AIC_QDE_ENT.BRANCH_ID
     *
     * @param branchId the value for FIS.AIC_QDE_ENT.BRANCH_ID
     *
     * @mbggenerated Mon Dec 09 09:10:11 CST 2013
     */
    public void setBranchId(String branchId) {
        this.branchId = branchId == null ? null : branchId.trim();
    }
}