package org.fbi.aicqde.repository.model;

import java.math.BigDecimal;

public class AicQdeInvester {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.AIC_QDE_INVESTER.PKID
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.AIC_QDE_INVESTER.REG_NO
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    private String regNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.AIC_QDE_INVESTER.VCH_SN
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    private String vchSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.AIC_QDE_INVESTER.INVESTER_NAME
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    private String investerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.AIC_QDE_INVESTER.ACT_NO
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    private String actNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.AIC_QDE_INVESTER.INV_AMT
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    private BigDecimal invAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.AIC_QDE_INVESTER.INV_DATE
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    private String invDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.AIC_QDE_INVESTER.ACT_BANK_NAME
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    private String actBankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.AIC_QDE_INVESTER.CERT_ID
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    private String certId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.AIC_QDE_INVESTER.INVEST_TYPE
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    private String investType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.AIC_QDE_INVESTER.BANK_HOST_SN
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    private String bankHostSn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.AIC_QDE_INVESTER.PKID
     *
     * @return the value of FIS.AIC_QDE_INVESTER.PKID
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.AIC_QDE_INVESTER.PKID
     *
     * @param pkid the value for FIS.AIC_QDE_INVESTER.PKID
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.AIC_QDE_INVESTER.REG_NO
     *
     * @return the value of FIS.AIC_QDE_INVESTER.REG_NO
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    public String getRegNo() {
        return regNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.AIC_QDE_INVESTER.REG_NO
     *
     * @param regNo the value for FIS.AIC_QDE_INVESTER.REG_NO
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    public void setRegNo(String regNo) {
        this.regNo = regNo == null ? null : regNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.AIC_QDE_INVESTER.VCH_SN
     *
     * @return the value of FIS.AIC_QDE_INVESTER.VCH_SN
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    public String getVchSn() {
        return vchSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.AIC_QDE_INVESTER.VCH_SN
     *
     * @param vchSn the value for FIS.AIC_QDE_INVESTER.VCH_SN
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    public void setVchSn(String vchSn) {
        this.vchSn = vchSn == null ? null : vchSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.AIC_QDE_INVESTER.INVESTER_NAME
     *
     * @return the value of FIS.AIC_QDE_INVESTER.INVESTER_NAME
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    public String getInvesterName() {
        return investerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.AIC_QDE_INVESTER.INVESTER_NAME
     *
     * @param investerName the value for FIS.AIC_QDE_INVESTER.INVESTER_NAME
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    public void setInvesterName(String investerName) {
        this.investerName = investerName == null ? null : investerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.AIC_QDE_INVESTER.ACT_NO
     *
     * @return the value of FIS.AIC_QDE_INVESTER.ACT_NO
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    public String getActNo() {
        return actNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.AIC_QDE_INVESTER.ACT_NO
     *
     * @param actNo the value for FIS.AIC_QDE_INVESTER.ACT_NO
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    public void setActNo(String actNo) {
        this.actNo = actNo == null ? null : actNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.AIC_QDE_INVESTER.INV_AMT
     *
     * @return the value of FIS.AIC_QDE_INVESTER.INV_AMT
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    public BigDecimal getInvAmt() {
        return invAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.AIC_QDE_INVESTER.INV_AMT
     *
     * @param invAmt the value for FIS.AIC_QDE_INVESTER.INV_AMT
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    public void setInvAmt(BigDecimal invAmt) {
        this.invAmt = invAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.AIC_QDE_INVESTER.INV_DATE
     *
     * @return the value of FIS.AIC_QDE_INVESTER.INV_DATE
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    public String getInvDate() {
        return invDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.AIC_QDE_INVESTER.INV_DATE
     *
     * @param invDate the value for FIS.AIC_QDE_INVESTER.INV_DATE
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    public void setInvDate(String invDate) {
        this.invDate = invDate == null ? null : invDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.AIC_QDE_INVESTER.ACT_BANK_NAME
     *
     * @return the value of FIS.AIC_QDE_INVESTER.ACT_BANK_NAME
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    public String getActBankName() {
        return actBankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.AIC_QDE_INVESTER.ACT_BANK_NAME
     *
     * @param actBankName the value for FIS.AIC_QDE_INVESTER.ACT_BANK_NAME
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    public void setActBankName(String actBankName) {
        this.actBankName = actBankName == null ? null : actBankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.AIC_QDE_INVESTER.CERT_ID
     *
     * @return the value of FIS.AIC_QDE_INVESTER.CERT_ID
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    public String getCertId() {
        return certId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.AIC_QDE_INVESTER.CERT_ID
     *
     * @param certId the value for FIS.AIC_QDE_INVESTER.CERT_ID
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    public void setCertId(String certId) {
        this.certId = certId == null ? null : certId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.AIC_QDE_INVESTER.INVEST_TYPE
     *
     * @return the value of FIS.AIC_QDE_INVESTER.INVEST_TYPE
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    public String getInvestType() {
        return investType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.AIC_QDE_INVESTER.INVEST_TYPE
     *
     * @param investType the value for FIS.AIC_QDE_INVESTER.INVEST_TYPE
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    public void setInvestType(String investType) {
        this.investType = investType == null ? null : investType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.AIC_QDE_INVESTER.BANK_HOST_SN
     *
     * @return the value of FIS.AIC_QDE_INVESTER.BANK_HOST_SN
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    public String getBankHostSn() {
        return bankHostSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.AIC_QDE_INVESTER.BANK_HOST_SN
     *
     * @param bankHostSn the value for FIS.AIC_QDE_INVESTER.BANK_HOST_SN
     *
     * @mbggenerated Wed Dec 11 10:16:04 CST 2013
     */
    public void setBankHostSn(String bankHostSn) {
        this.bankHostSn = bankHostSn == null ? null : bankHostSn.trim();
    }
}