package org.fbi.aicqde.repository.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class AicQdeEntExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.AIC_QDE_ENT
     *
     * @mbggenerated Wed Dec 11 11:35:40 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.AIC_QDE_ENT
     *
     * @mbggenerated Wed Dec 11 11:35:40 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.AIC_QDE_ENT
     *
     * @mbggenerated Wed Dec 11 11:35:40 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.AIC_QDE_ENT
     *
     * @mbggenerated Wed Dec 11 11:35:40 CST 2013
     */
    public AicQdeEntExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.AIC_QDE_ENT
     *
     * @mbggenerated Wed Dec 11 11:35:40 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.AIC_QDE_ENT
     *
     * @mbggenerated Wed Dec 11 11:35:40 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.AIC_QDE_ENT
     *
     * @mbggenerated Wed Dec 11 11:35:40 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.AIC_QDE_ENT
     *
     * @mbggenerated Wed Dec 11 11:35:40 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.AIC_QDE_ENT
     *
     * @mbggenerated Wed Dec 11 11:35:40 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.AIC_QDE_ENT
     *
     * @mbggenerated Wed Dec 11 11:35:40 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.AIC_QDE_ENT
     *
     * @mbggenerated Wed Dec 11 11:35:40 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.AIC_QDE_ENT
     *
     * @mbggenerated Wed Dec 11 11:35:40 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.AIC_QDE_ENT
     *
     * @mbggenerated Wed Dec 11 11:35:40 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.AIC_QDE_ENT
     *
     * @mbggenerated Wed Dec 11 11:35:40 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.AIC_QDE_ENT
     *
     * @mbggenerated Wed Dec 11 11:35:40 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPregNoIsNull() {
            addCriterion("PREG_NO is null");
            return (Criteria) this;
        }

        public Criteria andPregNoIsNotNull() {
            addCriterion("PREG_NO is not null");
            return (Criteria) this;
        }

        public Criteria andPregNoEqualTo(String value) {
            addCriterion("PREG_NO =", value, "pregNo");
            return (Criteria) this;
        }

        public Criteria andPregNoNotEqualTo(String value) {
            addCriterion("PREG_NO <>", value, "pregNo");
            return (Criteria) this;
        }

        public Criteria andPregNoGreaterThan(String value) {
            addCriterion("PREG_NO >", value, "pregNo");
            return (Criteria) this;
        }

        public Criteria andPregNoGreaterThanOrEqualTo(String value) {
            addCriterion("PREG_NO >=", value, "pregNo");
            return (Criteria) this;
        }

        public Criteria andPregNoLessThan(String value) {
            addCriterion("PREG_NO <", value, "pregNo");
            return (Criteria) this;
        }

        public Criteria andPregNoLessThanOrEqualTo(String value) {
            addCriterion("PREG_NO <=", value, "pregNo");
            return (Criteria) this;
        }

        public Criteria andPregNoLike(String value) {
            addCriterion("PREG_NO like", value, "pregNo");
            return (Criteria) this;
        }

        public Criteria andPregNoNotLike(String value) {
            addCriterion("PREG_NO not like", value, "pregNo");
            return (Criteria) this;
        }

        public Criteria andPregNoIn(List<String> values) {
            addCriterion("PREG_NO in", values, "pregNo");
            return (Criteria) this;
        }

        public Criteria andPregNoNotIn(List<String> values) {
            addCriterion("PREG_NO not in", values, "pregNo");
            return (Criteria) this;
        }

        public Criteria andPregNoBetween(String value1, String value2) {
            addCriterion("PREG_NO between", value1, value2, "pregNo");
            return (Criteria) this;
        }

        public Criteria andPregNoNotBetween(String value1, String value2) {
            addCriterion("PREG_NO not between", value1, value2, "pregNo");
            return (Criteria) this;
        }

        public Criteria andAreaCodeIsNull() {
            addCriterion("AREA_CODE is null");
            return (Criteria) this;
        }

        public Criteria andAreaCodeIsNotNull() {
            addCriterion("AREA_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andAreaCodeEqualTo(String value) {
            addCriterion("AREA_CODE =", value, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeNotEqualTo(String value) {
            addCriterion("AREA_CODE <>", value, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeGreaterThan(String value) {
            addCriterion("AREA_CODE >", value, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeGreaterThanOrEqualTo(String value) {
            addCriterion("AREA_CODE >=", value, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeLessThan(String value) {
            addCriterion("AREA_CODE <", value, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeLessThanOrEqualTo(String value) {
            addCriterion("AREA_CODE <=", value, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeLike(String value) {
            addCriterion("AREA_CODE like", value, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeNotLike(String value) {
            addCriterion("AREA_CODE not like", value, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeIn(List<String> values) {
            addCriterion("AREA_CODE in", values, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeNotIn(List<String> values) {
            addCriterion("AREA_CODE not in", values, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeBetween(String value1, String value2) {
            addCriterion("AREA_CODE between", value1, value2, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAreaCodeNotBetween(String value1, String value2) {
            addCriterion("AREA_CODE not between", value1, value2, "areaCode");
            return (Criteria) this;
        }

        public Criteria andAicCodeIsNull() {
            addCriterion("AIC_CODE is null");
            return (Criteria) this;
        }

        public Criteria andAicCodeIsNotNull() {
            addCriterion("AIC_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andAicCodeEqualTo(String value) {
            addCriterion("AIC_CODE =", value, "aicCode");
            return (Criteria) this;
        }

        public Criteria andAicCodeNotEqualTo(String value) {
            addCriterion("AIC_CODE <>", value, "aicCode");
            return (Criteria) this;
        }

        public Criteria andAicCodeGreaterThan(String value) {
            addCriterion("AIC_CODE >", value, "aicCode");
            return (Criteria) this;
        }

        public Criteria andAicCodeGreaterThanOrEqualTo(String value) {
            addCriterion("AIC_CODE >=", value, "aicCode");
            return (Criteria) this;
        }

        public Criteria andAicCodeLessThan(String value) {
            addCriterion("AIC_CODE <", value, "aicCode");
            return (Criteria) this;
        }

        public Criteria andAicCodeLessThanOrEqualTo(String value) {
            addCriterion("AIC_CODE <=", value, "aicCode");
            return (Criteria) this;
        }

        public Criteria andAicCodeLike(String value) {
            addCriterion("AIC_CODE like", value, "aicCode");
            return (Criteria) this;
        }

        public Criteria andAicCodeNotLike(String value) {
            addCriterion("AIC_CODE not like", value, "aicCode");
            return (Criteria) this;
        }

        public Criteria andAicCodeIn(List<String> values) {
            addCriterion("AIC_CODE in", values, "aicCode");
            return (Criteria) this;
        }

        public Criteria andAicCodeNotIn(List<String> values) {
            addCriterion("AIC_CODE not in", values, "aicCode");
            return (Criteria) this;
        }

        public Criteria andAicCodeBetween(String value1, String value2) {
            addCriterion("AIC_CODE between", value1, value2, "aicCode");
            return (Criteria) this;
        }

        public Criteria andAicCodeNotBetween(String value1, String value2) {
            addCriterion("AIC_CODE not between", value1, value2, "aicCode");
            return (Criteria) this;
        }

        public Criteria andAicNameIsNull() {
            addCriterion("AIC_NAME is null");
            return (Criteria) this;
        }

        public Criteria andAicNameIsNotNull() {
            addCriterion("AIC_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andAicNameEqualTo(String value) {
            addCriterion("AIC_NAME =", value, "aicName");
            return (Criteria) this;
        }

        public Criteria andAicNameNotEqualTo(String value) {
            addCriterion("AIC_NAME <>", value, "aicName");
            return (Criteria) this;
        }

        public Criteria andAicNameGreaterThan(String value) {
            addCriterion("AIC_NAME >", value, "aicName");
            return (Criteria) this;
        }

        public Criteria andAicNameGreaterThanOrEqualTo(String value) {
            addCriterion("AIC_NAME >=", value, "aicName");
            return (Criteria) this;
        }

        public Criteria andAicNameLessThan(String value) {
            addCriterion("AIC_NAME <", value, "aicName");
            return (Criteria) this;
        }

        public Criteria andAicNameLessThanOrEqualTo(String value) {
            addCriterion("AIC_NAME <=", value, "aicName");
            return (Criteria) this;
        }

        public Criteria andAicNameLike(String value) {
            addCriterion("AIC_NAME like", value, "aicName");
            return (Criteria) this;
        }

        public Criteria andAicNameNotLike(String value) {
            addCriterion("AIC_NAME not like", value, "aicName");
            return (Criteria) this;
        }

        public Criteria andAicNameIn(List<String> values) {
            addCriterion("AIC_NAME in", values, "aicName");
            return (Criteria) this;
        }

        public Criteria andAicNameNotIn(List<String> values) {
            addCriterion("AIC_NAME not in", values, "aicName");
            return (Criteria) this;
        }

        public Criteria andAicNameBetween(String value1, String value2) {
            addCriterion("AIC_NAME between", value1, value2, "aicName");
            return (Criteria) this;
        }

        public Criteria andAicNameNotBetween(String value1, String value2) {
            addCriterion("AIC_NAME not between", value1, value2, "aicName");
            return (Criteria) this;
        }

        public Criteria andRegNoIsNull() {
            addCriterion("REG_NO is null");
            return (Criteria) this;
        }

        public Criteria andRegNoIsNotNull() {
            addCriterion("REG_NO is not null");
            return (Criteria) this;
        }

        public Criteria andRegNoEqualTo(String value) {
            addCriterion("REG_NO =", value, "regNo");
            return (Criteria) this;
        }

        public Criteria andRegNoNotEqualTo(String value) {
            addCriterion("REG_NO <>", value, "regNo");
            return (Criteria) this;
        }

        public Criteria andRegNoGreaterThan(String value) {
            addCriterion("REG_NO >", value, "regNo");
            return (Criteria) this;
        }

        public Criteria andRegNoGreaterThanOrEqualTo(String value) {
            addCriterion("REG_NO >=", value, "regNo");
            return (Criteria) this;
        }

        public Criteria andRegNoLessThan(String value) {
            addCriterion("REG_NO <", value, "regNo");
            return (Criteria) this;
        }

        public Criteria andRegNoLessThanOrEqualTo(String value) {
            addCriterion("REG_NO <=", value, "regNo");
            return (Criteria) this;
        }

        public Criteria andRegNoLike(String value) {
            addCriterion("REG_NO like", value, "regNo");
            return (Criteria) this;
        }

        public Criteria andRegNoNotLike(String value) {
            addCriterion("REG_NO not like", value, "regNo");
            return (Criteria) this;
        }

        public Criteria andRegNoIn(List<String> values) {
            addCriterion("REG_NO in", values, "regNo");
            return (Criteria) this;
        }

        public Criteria andRegNoNotIn(List<String> values) {
            addCriterion("REG_NO not in", values, "regNo");
            return (Criteria) this;
        }

        public Criteria andRegNoBetween(String value1, String value2) {
            addCriterion("REG_NO between", value1, value2, "regNo");
            return (Criteria) this;
        }

        public Criteria andRegNoNotBetween(String value1, String value2) {
            addCriterion("REG_NO not between", value1, value2, "regNo");
            return (Criteria) this;
        }

        public Criteria andActNoIsNull() {
            addCriterion("ACT_NO is null");
            return (Criteria) this;
        }

        public Criteria andActNoIsNotNull() {
            addCriterion("ACT_NO is not null");
            return (Criteria) this;
        }

        public Criteria andActNoEqualTo(String value) {
            addCriterion("ACT_NO =", value, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoNotEqualTo(String value) {
            addCriterion("ACT_NO <>", value, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoGreaterThan(String value) {
            addCriterion("ACT_NO >", value, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoGreaterThanOrEqualTo(String value) {
            addCriterion("ACT_NO >=", value, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoLessThan(String value) {
            addCriterion("ACT_NO <", value, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoLessThanOrEqualTo(String value) {
            addCriterion("ACT_NO <=", value, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoLike(String value) {
            addCriterion("ACT_NO like", value, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoNotLike(String value) {
            addCriterion("ACT_NO not like", value, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoIn(List<String> values) {
            addCriterion("ACT_NO in", values, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoNotIn(List<String> values) {
            addCriterion("ACT_NO not in", values, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoBetween(String value1, String value2) {
            addCriterion("ACT_NO between", value1, value2, "actNo");
            return (Criteria) this;
        }

        public Criteria andActNoNotBetween(String value1, String value2) {
            addCriterion("ACT_NO not between", value1, value2, "actNo");
            return (Criteria) this;
        }

        public Criteria andActBalIsNull() {
            addCriterion("ACT_BAL is null");
            return (Criteria) this;
        }

        public Criteria andActBalIsNotNull() {
            addCriterion("ACT_BAL is not null");
            return (Criteria) this;
        }

        public Criteria andActBalEqualTo(BigDecimal value) {
            addCriterion("ACT_BAL =", value, "actBal");
            return (Criteria) this;
        }

        public Criteria andActBalNotEqualTo(BigDecimal value) {
            addCriterion("ACT_BAL <>", value, "actBal");
            return (Criteria) this;
        }

        public Criteria andActBalGreaterThan(BigDecimal value) {
            addCriterion("ACT_BAL >", value, "actBal");
            return (Criteria) this;
        }

        public Criteria andActBalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ACT_BAL >=", value, "actBal");
            return (Criteria) this;
        }

        public Criteria andActBalLessThan(BigDecimal value) {
            addCriterion("ACT_BAL <", value, "actBal");
            return (Criteria) this;
        }

        public Criteria andActBalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ACT_BAL <=", value, "actBal");
            return (Criteria) this;
        }

        public Criteria andActBalIn(List<BigDecimal> values) {
            addCriterion("ACT_BAL in", values, "actBal");
            return (Criteria) this;
        }

        public Criteria andActBalNotIn(List<BigDecimal> values) {
            addCriterion("ACT_BAL not in", values, "actBal");
            return (Criteria) this;
        }

        public Criteria andActBalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACT_BAL between", value1, value2, "actBal");
            return (Criteria) this;
        }

        public Criteria andActBalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACT_BAL not between", value1, value2, "actBal");
            return (Criteria) this;
        }

        public Criteria andBankHostSnIsNull() {
            addCriterion("BANK_HOST_SN is null");
            return (Criteria) this;
        }

        public Criteria andBankHostSnIsNotNull() {
            addCriterion("BANK_HOST_SN is not null");
            return (Criteria) this;
        }

        public Criteria andBankHostSnEqualTo(String value) {
            addCriterion("BANK_HOST_SN =", value, "bankHostSn");
            return (Criteria) this;
        }

        public Criteria andBankHostSnNotEqualTo(String value) {
            addCriterion("BANK_HOST_SN <>", value, "bankHostSn");
            return (Criteria) this;
        }

        public Criteria andBankHostSnGreaterThan(String value) {
            addCriterion("BANK_HOST_SN >", value, "bankHostSn");
            return (Criteria) this;
        }

        public Criteria andBankHostSnGreaterThanOrEqualTo(String value) {
            addCriterion("BANK_HOST_SN >=", value, "bankHostSn");
            return (Criteria) this;
        }

        public Criteria andBankHostSnLessThan(String value) {
            addCriterion("BANK_HOST_SN <", value, "bankHostSn");
            return (Criteria) this;
        }

        public Criteria andBankHostSnLessThanOrEqualTo(String value) {
            addCriterion("BANK_HOST_SN <=", value, "bankHostSn");
            return (Criteria) this;
        }

        public Criteria andBankHostSnLike(String value) {
            addCriterion("BANK_HOST_SN like", value, "bankHostSn");
            return (Criteria) this;
        }

        public Criteria andBankHostSnNotLike(String value) {
            addCriterion("BANK_HOST_SN not like", value, "bankHostSn");
            return (Criteria) this;
        }

        public Criteria andBankHostSnIn(List<String> values) {
            addCriterion("BANK_HOST_SN in", values, "bankHostSn");
            return (Criteria) this;
        }

        public Criteria andBankHostSnNotIn(List<String> values) {
            addCriterion("BANK_HOST_SN not in", values, "bankHostSn");
            return (Criteria) this;
        }

        public Criteria andBankHostSnBetween(String value1, String value2) {
            addCriterion("BANK_HOST_SN between", value1, value2, "bankHostSn");
            return (Criteria) this;
        }

        public Criteria andBankHostSnNotBetween(String value1, String value2) {
            addCriterion("BANK_HOST_SN not between", value1, value2, "bankHostSn");
            return (Criteria) this;
        }

        public Criteria andBankNameIsNull() {
            addCriterion("BANK_NAME is null");
            return (Criteria) this;
        }

        public Criteria andBankNameIsNotNull() {
            addCriterion("BANK_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andBankNameEqualTo(String value) {
            addCriterion("BANK_NAME =", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotEqualTo(String value) {
            addCriterion("BANK_NAME <>", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameGreaterThan(String value) {
            addCriterion("BANK_NAME >", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameGreaterThanOrEqualTo(String value) {
            addCriterion("BANK_NAME >=", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLessThan(String value) {
            addCriterion("BANK_NAME <", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLessThanOrEqualTo(String value) {
            addCriterion("BANK_NAME <=", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLike(String value) {
            addCriterion("BANK_NAME like", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotLike(String value) {
            addCriterion("BANK_NAME not like", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameIn(List<String> values) {
            addCriterion("BANK_NAME in", values, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotIn(List<String> values) {
            addCriterion("BANK_NAME not in", values, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameBetween(String value1, String value2) {
            addCriterion("BANK_NAME between", value1, value2, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotBetween(String value1, String value2) {
            addCriterion("BANK_NAME not between", value1, value2, "bankName");
            return (Criteria) this;
        }

        public Criteria andEntNameIsNull() {
            addCriterion("ENT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andEntNameIsNotNull() {
            addCriterion("ENT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andEntNameEqualTo(String value) {
            addCriterion("ENT_NAME =", value, "entName");
            return (Criteria) this;
        }

        public Criteria andEntNameNotEqualTo(String value) {
            addCriterion("ENT_NAME <>", value, "entName");
            return (Criteria) this;
        }

        public Criteria andEntNameGreaterThan(String value) {
            addCriterion("ENT_NAME >", value, "entName");
            return (Criteria) this;
        }

        public Criteria andEntNameGreaterThanOrEqualTo(String value) {
            addCriterion("ENT_NAME >=", value, "entName");
            return (Criteria) this;
        }

        public Criteria andEntNameLessThan(String value) {
            addCriterion("ENT_NAME <", value, "entName");
            return (Criteria) this;
        }

        public Criteria andEntNameLessThanOrEqualTo(String value) {
            addCriterion("ENT_NAME <=", value, "entName");
            return (Criteria) this;
        }

        public Criteria andEntNameLike(String value) {
            addCriterion("ENT_NAME like", value, "entName");
            return (Criteria) this;
        }

        public Criteria andEntNameNotLike(String value) {
            addCriterion("ENT_NAME not like", value, "entName");
            return (Criteria) this;
        }

        public Criteria andEntNameIn(List<String> values) {
            addCriterion("ENT_NAME in", values, "entName");
            return (Criteria) this;
        }

        public Criteria andEntNameNotIn(List<String> values) {
            addCriterion("ENT_NAME not in", values, "entName");
            return (Criteria) this;
        }

        public Criteria andEntNameBetween(String value1, String value2) {
            addCriterion("ENT_NAME between", value1, value2, "entName");
            return (Criteria) this;
        }

        public Criteria andEntNameNotBetween(String value1, String value2) {
            addCriterion("ENT_NAME not between", value1, value2, "entName");
            return (Criteria) this;
        }

        public Criteria andTellerIdIsNull() {
            addCriterion("TELLER_ID is null");
            return (Criteria) this;
        }

        public Criteria andTellerIdIsNotNull() {
            addCriterion("TELLER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTellerIdEqualTo(String value) {
            addCriterion("TELLER_ID =", value, "tellerId");
            return (Criteria) this;
        }

        public Criteria andTellerIdNotEqualTo(String value) {
            addCriterion("TELLER_ID <>", value, "tellerId");
            return (Criteria) this;
        }

        public Criteria andTellerIdGreaterThan(String value) {
            addCriterion("TELLER_ID >", value, "tellerId");
            return (Criteria) this;
        }

        public Criteria andTellerIdGreaterThanOrEqualTo(String value) {
            addCriterion("TELLER_ID >=", value, "tellerId");
            return (Criteria) this;
        }

        public Criteria andTellerIdLessThan(String value) {
            addCriterion("TELLER_ID <", value, "tellerId");
            return (Criteria) this;
        }

        public Criteria andTellerIdLessThanOrEqualTo(String value) {
            addCriterion("TELLER_ID <=", value, "tellerId");
            return (Criteria) this;
        }

        public Criteria andTellerIdLike(String value) {
            addCriterion("TELLER_ID like", value, "tellerId");
            return (Criteria) this;
        }

        public Criteria andTellerIdNotLike(String value) {
            addCriterion("TELLER_ID not like", value, "tellerId");
            return (Criteria) this;
        }

        public Criteria andTellerIdIn(List<String> values) {
            addCriterion("TELLER_ID in", values, "tellerId");
            return (Criteria) this;
        }

        public Criteria andTellerIdNotIn(List<String> values) {
            addCriterion("TELLER_ID not in", values, "tellerId");
            return (Criteria) this;
        }

        public Criteria andTellerIdBetween(String value1, String value2) {
            addCriterion("TELLER_ID between", value1, value2, "tellerId");
            return (Criteria) this;
        }

        public Criteria andTellerIdNotBetween(String value1, String value2) {
            addCriterion("TELLER_ID not between", value1, value2, "tellerId");
            return (Criteria) this;
        }

        public Criteria andBranchIdIsNull() {
            addCriterion("BRANCH_ID is null");
            return (Criteria) this;
        }

        public Criteria andBranchIdIsNotNull() {
            addCriterion("BRANCH_ID is not null");
            return (Criteria) this;
        }

        public Criteria andBranchIdEqualTo(String value) {
            addCriterion("BRANCH_ID =", value, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdNotEqualTo(String value) {
            addCriterion("BRANCH_ID <>", value, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdGreaterThan(String value) {
            addCriterion("BRANCH_ID >", value, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdGreaterThanOrEqualTo(String value) {
            addCriterion("BRANCH_ID >=", value, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdLessThan(String value) {
            addCriterion("BRANCH_ID <", value, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdLessThanOrEqualTo(String value) {
            addCriterion("BRANCH_ID <=", value, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdLike(String value) {
            addCriterion("BRANCH_ID like", value, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdNotLike(String value) {
            addCriterion("BRANCH_ID not like", value, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdIn(List<String> values) {
            addCriterion("BRANCH_ID in", values, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdNotIn(List<String> values) {
            addCriterion("BRANCH_ID not in", values, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdBetween(String value1, String value2) {
            addCriterion("BRANCH_ID between", value1, value2, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdNotBetween(String value1, String value2) {
            addCriterion("BRANCH_ID not between", value1, value2, "branchId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.AIC_QDE_ENT
     *
     * @mbggenerated do_not_delete_during_merge Wed Dec 11 11:35:40 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.AIC_QDE_ENT
     *
     * @mbggenerated Wed Dec 11 11:35:40 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}